### ISSUE TITLE
No Cloudflare?

### ISSUE THREAD

**Issue by Lvl4Sword** [dustball/secretchat.site#2]
Right now your IP is out in the open to anyone who pings or accesses the site. Are you worried about a DDoS or other attack on your server?

**Comment by dustball** [comment]
Do you know if Cloudflare supports socket.io / node.js?

Or does it act as a proxy?

**Comment by dustball** [comment]
Okay, I have actually activated Cloudflare on securesocket.io.  It will be
4-6 hours before DNS propogates.

**Comment by dustball** [comment]
Hey, this was a great suggestion.  Thanks.  It seems to be working already
from my end.

**Comment by Lvl4Sword** [comment]
The only issue with Cloudflare is that all https traffic is man-in-the-middled. So, yeah that's a thing.

**Comment by dustball** [comment]
Ha. Well.  I'm the weakest link in the chain, for sure.

But again, client-side AES encryption & decryption, solves the issue.

**Comment by dustball** [comment]
Cloudflare now enabled on both securesocket.io and secretchat.site.
