### ISSUE TITLE
Errors are inconsistent

### ISSUE THREAD

**Issue by Lvl4Sword** [dustball/secretchat.site#3]
https://secretchat.site/room/ gives a status code of 200
and
https://secretchat.site/TEST/ gives a status code of 404

I'd suggest if someone directly accesses something, you execute some server-side code.
Such as, anything that would be 403 should route to 404. Then the 404 page should have something like this:

```
<?php
http_response_code(404);
?>
```

Which makes it harder to tell whether something is truly not there, or forbidden.

**Comment by dustball** [comment]
Issue resolved -- I think.

**Comment by dustball** [comment]
See also 2630e17

**Comment by Lvl4Sword** [comment]
Yep, that fixed it. You should get a fancier 404 page though :smiley:

**Comment by dustball** [comment]
Patches welcome ;)

**Comment by dustball** [comment]
Fixed with bd42eaf.
