### ISSUE TITLE
Generation of Rooms

### ISSUE THREAD

**Issue by Lvl4Sword** [dustball/secretchat.site#4]
Couple issues.
1. You're using input for the room and just wrapping it in a sha1 function.
2. What exactly are you using to "encrypt" conversations, and why do users not have access to their own keys ( and preferably, can generate their own )?
3. Why does "password" need to equal the sha1 hashed room name? What's password even for?

**Comment by dustball** [comment]
Okay, two things to keep separate.

1) All encryption is done using the password entered on room.php.  That is
the key (quite literally) to encryption and decryption.  This answers #2 of
your questiom, in that the user does choose the enc/dec key.

2) The password is ALSO used as a convenience for creating a distinct room
URL.  This is for convenience.  It provides a way to make sure they entered
they password correctly, that is all.  Otherwise if you decrypt with the
wrong password, it just comes at as garbled.  So yes #1 is correct, but
purely again as convenience.  Also addresses #3 directly.

Hope that helps.

-B

**Comment by Lvl4Sword** [comment]
Ok, level with me for a second.
So when I send someone a room link ( https://secretchat.site/room/0ae9e4deba26021986ffd99636da6601f6393631 for "elephant" ) they still need to type in the room name to get in.
So you need to let them know the room name in advance.
Which, would mean that you need to let them know it in a secure fashion.
Like OTR, PGP, Signal, or something else.
Which, kind of defeats the point of the site.

Or am I missing something?

**Comment by dustball** [comment]
Yes, you need a way to get the key to them in advance.

This is not difficult for the use cases I imagine.

Most people don't understand PGP or public key crypto.

Requiring a shared secret helps ensure that Bob is who Alice thinks Bob is.

**Comment by dustball** [comment]
I mean a simple phonecall solves the shared key problem.

**Comment by skifree-snowmonster** [comment]
**This is redundant and pointless. Sha1 is broken and has been for some time.** Use sha256 if you plan on basing your room name privacy model around hashes. Also, consider salting them or setting the HMAC with a password users need to know for entry instead.

Example:

Channel name: I_love_elephants
HMAC: anyonehereisallowed
Link becomes: https://secretchat.site/room/33aa9dcfc7beaded440572febdbe793123991cd85529120a9bdb31388f2b7547

**Comment by Lvl4Sword** [comment]
There are multiple issues with your approach.

You are giving a sha1 hash of the room which anyone paying attention to the connection could attempt to bruteforce.
You're also not even adding a random salt to the room sha1.
You shouldn't be using sha1 ( https://www.schneier.com/blog/archives/2005/02/sha1_broken.html ) - THIS DATES BACK TO 2005. IT'S BEEN BROKEN FOR MORE THAN A DECADE!

Take a look at https://passlib.readthedocs.io/en/stable/ and https://docs.python.org/2/library/hashlib.html

OTR encrypted chats, and Signal have Perfect Forward Secrecy. Thus both would be much better than your site.

**Comment by dustball** [comment]
Sn0wmonster - I get a 404 when trying your link.  The hash is too long.

Thank you, regardless.  I will upgrade to sha256.

**Comment by skifree-snowmonster** [comment]
The link example was based on an implementation having used sha256 with an HMAC. Since your site doesn't, of course the link doesn't work.

**Comment by Lvl4Sword** [comment]
Sn0wmonster was recommending you use an HMAC and that the URL they gave you would have been the final URL.

**Comment by denkweise9** [comment]
![00000000000](https://cloud.githubusercontent.com/assets/24786363/21491147/a66d932c-cbc8-11e6-8cb9-8fef1879c2f2.png)

Sir, not to kick you down, but the fact I was able to access a 'secret' conversation by entering the 'elephant' room without needing any programming experience shows the level of security that this site uses.

Anyone can take a SHA1 hash and reverse it without being told the name.
This URL does just that,  https://hashkiller.co.uk/sha1-decrypter.aspx  <------------- "Tested elephant"


The fact that this hash (which is just the name of the room anyways) is used to 'encrypt' anything is scary.  How is this secure if a script kiddie can get access so easily?

Saying that "Most people don't understand PGP.." does not make your software any more secure. Nor does it debunk any thesis that your software is insecure.
Pidign, Hexchat, etc are clients that take care of GPG,PGP, etc for you so you don't need to understand them anyways. 

*It doesn't require advanced technical skills to use Signal or OTR. Seriously*
And no, "a simple phone call" is not going to fix the problem.


If someone were experienced with multiple languages, such as JavaScript, Java, Python, PHP, etc. 
I would have no doubt that they would be able to create havoc or serious damage.   



Please take time to research more into the security aspect of something if you are serious about 'security'.

**Comment by dustball** [comment]
So you used a weak key and are surprised that you can find a matching hash.  

Anyway, I already said sha256 sounds like a good idea, as well as salts.

Patches welcome, or you can continue throwing stones if that is all you want to do.

**Comment by dustball** [comment]
Commit f867ab8 resolves this issue.
