### ISSUE TITLE
Use of cryptographically insecure PRNG

### ISSUE THREAD

**Issue by EdOverflow** [dustball/secretchat.site#6]
Hi @dustball,

# Summary

A PRNG is an algorithm used to produce random-looking numbers with certain desirable statistical properties. In order for a PRNG to be cryptographically secure it must be resistant to prediction.

secretchat.site currently uses `Math.random()` as a pseudo-random number generator which is not a cryptographically secure PRNG.

The PRNG is implemented in `room.php` when generating an IV as follows:

~~~
function make_iv() {
        var text = "";
        var possible = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
        for( var i=0; i < 16; i++ )
          text += possible.charAt(Math.floor(Math.random() * possible.length));
        return text;
}
~~~

Link to source code: https://github.com/dustball/secretchat.site/blob/master/www/room.php#L234-L240

The PRNG is again implemented in `index.php` to generate salts:

~~~
function make_salt() {
  var text = "";
  var possible = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
  for( var i=0; i < 16; i++ )
    text += possible.charAt(Math.floor(Math.random() * possible.length));
  return text;
}
~~~

Link to source code: https://github.com/dustball/secretchat.site/blob/master/www/index.php#L94-L100

# How can this be fixed?

You could either implement a CPRNG from a library or use the [Web Crypto API](https://developer.mozilla.org/en-US/docs/Web/API/RandomSource/getRandomValues). 

Best regards,
Ed

**Comment by dustball** [comment]
Thank you!  Yet another thing I've learned today.

I was able to update each function to use the Web Crypto API.  I pick one random number at a time, and take that modulo the length of my string array for a random character * 16.

Resolved with 8bb50d4.
