### ISSUE TITLE
Remove Google analytics

### ISSUE THREAD

**Issue by EdOverflow** [dustball/secretchat.site#7]
The following comment claims that you do not use Google analytics in the production version, but as far as I can tell you have deployed this page without removing the analytics code snippet:

> // production version will not have google analytics

https://github.com/dustball/secretchat.site/blob/master/www/index.php#L111

**Comment by dustball** [comment]
Yes, you are correct.  It shall be removed.

**Comment by dustball** [comment]
Resolved with  a2bf467
