### ISSUE TITLE
Remove third party CDN libraries and dependencies

### ISSUE THREAD

**Issue by EdOverflow** [dustball/secretchat.site#8]
Please consider removing third party tracking software. You are better off including any necessary fonts, stylesheets, scripts, etc., in the project source.

**Comment by dustball** [comment]
I agree that Google Analytics & GetSocial should be removed.

However, for the CDN hosted javascript, there are arguments both for and against -- almost.  In fact I think I may try to convince you this is the safest way. 

1) With crypto-js hosted on secretchat.site, secretchat.site could replace the crypto-js code, replacing it with code that only makes it look encrypted. 

2) With crypto-js hosted on CDN, that moves the trust component to the CDN, so we must trust the CDN instead.

3) However, with Subresource Integrity enabled on the CDN, that creates a partnership between host and CDN where all requests for files are signed with SRI.  The CDN can't replace the code without it simply stopping work as the hash will not match.  See https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity for more information.

I motion that moving the scripts into the project will actually make it less secure, not more, unless you trust me completely, which of course should not be the case.

What do you think?

**Comment by EdOverflow** [comment]
Sorry, I did not specify which resource in particular. I am referring to `https://fonts.googleapis.com/css?family=Droid+Sans`. You can include fonts directly in the project source.

Also on a side note, you should not depend on SRI, since it is not supported by all modern browsers. [1] Other than that, I agree with the points mentioned above.

[1] - http://caniuse.com/#feat=subresource-integrity
